/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CalaAccount {
  id(): string
  values(): AccountValues
}

export declare class CalaAccounts {
  create(newAccount: NewAccount): Promise<CalaAccount>
  findByCode(code: string): Promise<CalaAccount>
  findById(accountId: string): Promise<CalaAccount>
  findByExternalId(externalId: string): Promise<CalaAccount>
  list(query: PaginatedQueryArgs): Promise<PaginatedAccounts>
}

export declare class CalaBalances {
  find(accountId: string, journalId: string, currency: string): Promise<BalanceValues>
}

export declare class CalaEntries {
  listByTransaction(transactionId: string): Promise<Array<EntryValues>>
  listForJournalId(journalId: string, query: PaginatedQueryArgs, direction?: ListDirection | undefined | null): Promise<PaginatedEntries>
  listForAccountId(accountId: string, query: PaginatedQueryArgs, direction?: ListDirection | undefined | null): Promise<PaginatedEntries>
}

export declare class CalaJournal {
  id(): string
  values(): JournalValues
}

export declare class CalaJournals {
  create(newJournal: NewJournal): Promise<CalaJournal>
  find(journalId: string): Promise<CalaJournal>
}

export declare class CalaLedger {
  static connect(config: CalaLedgerConfig): Promise<CalaLedger>
  accounts(): CalaAccounts
  journals(): CalaJournals
  txTemplates(): CalaTxTemplates
  balances(): CalaBalances
  entries(): CalaEntries
  transactions(): CalaTransactions
  awaitOutboxServer(): Promise<void>
}

export declare class CalaTransaction {
  id(): string
  values(): TransactionValues
}

export declare class CalaTransactions {
  findById(id: string): Promise<CalaTransaction>
  findByExternalId(externalId: string): Promise<CalaTransaction | null>
  post(txTemplateCode: string, params: any): Promise<CalaTransaction>
  voidTransaction(transactionId: string): Promise<CalaTransaction>
}

export declare class CalaTxTemplate {
  id(): string
  values(): TxTemplateValues
}

export declare class CalaTxTemplates {
  findByCode(code: string): Promise<CalaTxTemplate>
  create(newTxTemplate: NewTxTemplateValues): Promise<CalaTxTemplate>
  list(query: PaginatedQueryArgs, direction?: ListDirection | undefined | null): Promise<PaginatedTxTemplates>
}

export interface AccountValues {
  id: string
  code: string
  name: string
  externalId?: string
  description?: string
  metadata?: any
}

export interface BalanceValues {
  pending: string
  settled: string
  encumbrance: string
}

export interface CalaLedgerConfig {
  pgCon: string
  maxConnections?: number
  outbox?: OutboxServerConfig
}

export interface CursorToken {
  token: string
}

export interface EntryValues {
  id: string
  version: number
  transactionId: string
  journalId: string
  accountId: string
  entryType: string
  sequence: number
  layer: string
  units: string
  currency: string
  direction: string
  description?: string
  metadata?: any
}

export interface JournalValues {
  id: string
  name: string
  code?: string
  description?: string
}

export declare const enum ListDirection {
  Ascending = 0,
  Descending = 1
}

export interface NewAccount {
  id?: string
  code: string
  name: string
  externalId?: string
  description?: string
  metadata?: any
}

export interface NewJournal {
  id?: string
  name: string
  code?: string
  externalId?: string
  description?: string
}

export interface NewParamDefinitionValues {
  name: string
  type: ParamDataTypeValues
  default?: string
  description?: string
}

export interface NewTxTemplateEntryValues {
  entryType: string
  accountId: string
  layer: string
  direction: string
  units: string
  currency: string
  description?: string
  metadata?: string
}

export interface NewTxTemplateTransactionValues {
  effective: string
  journalId: string
  correlationId?: string
  externalId?: string
  description?: string
  metadata?: string
}

export interface NewTxTemplateValues {
  id?: string
  code: string
  externalId?: string
  description?: string
  params?: Array<NewParamDefinitionValues>
  entries: Array<NewTxTemplateEntryValues>
  metadata?: any
  transaction?: NewTxTemplateTransactionValues
}

export interface OutboxServerConfig {
  enabled: boolean
  listenPort?: number
}

export interface PaginatedAccounts {
  accounts: Array<AccountValues>
  hasNextPage: boolean
  endCursor?: CursorToken
}

export interface PaginatedEntries {
  entries: Array<EntryValues>
  hasNextPage: boolean
  endCursor?: CursorToken
}

export interface PaginatedQueryArgs {
  after?: CursorToken
  first: number
}

export interface PaginatedTxTemplates {
  txTemplates: Array<TxTemplateValues>
  hasNextPage: boolean
  endCursor?: CursorToken
}

export declare const enum ParamDataTypeValues {
  String = 0,
  Integer = 1,
  Decimal = 2,
  Boolean = 3,
  Uuid = 4,
  Date = 5,
  Timestamp = 6,
  Json = 7
}

export interface TransactionValues {
  id: string
  version: string
  createdAt: string
  modifiedAt: string
  journalId: string
  txTemplateId: string
  entryIds: Array<string>
  effective: string
  correlationId: string
  externalId?: string
  description?: string
  voidOf?: string
  voidedBy?: string
  metadata?: any
}

export interface TxTemplateValues {
  id: string
  code: string
  version: number
  metadata?: any
  description?: string
}
